import type { Metadata } from 'next';
import { Scada } from 'next/font/google';
import './globals.scss';

const scada = Scada({
  subsets: ['latin', 'latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-scada',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className='dark' lang='en'>
      <body suppressHydrationWarning className={scada.className}>
        {children}
      </body>
    </html>
  );
}
